# Generated by Django 4.0.2 on 2022-02-14 05:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insta', '0002_instapost_post_added'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfollow',
            unique_together={('user', 'follower')},
        ),
    ]
